name: hello_workflow
on: [push]

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Abner



