name: hello_workflow
on: [push]

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/javascript-action@v1
      - run: javascript -c "console.log('Olá Abner!!')"



